### PR TITLE
recreate the Vue.js boilerplate using vue-cli

### PR DESCRIPTION
**Pull request by floydpink**
# What does this PR Fix?
- Issue **n/a**

# Proposed Changes
 - convert to using TypeScript and class-style components
 - add Vuex and vue-router
 - add unit and e2e tests placeholders
 - add on-save and on-commit linters

- [x] Have you tested this code?

### CODE REVIEW

**Comment by floydpink** [comment]
@carrotfarmer - sorry for a really large overhaul - when I created the project originally, I did that using WebStorm's embedded/built-in (and really old) vue-cli

I recreated another project from scratch using the latest vue-cli and used advanced mix-and-match on the components to get to an (arguably) better starting point

**Comment by carrotfarmer** [comment]
@floydpink Cool Typescript! Even I wanted to migrate lol. I just have this one question:
- Do we really need `Vuex` for state management if we're gonna migrate to Vue v3? Vue3 has many helpful methods like the new `reactive` function which is kinda like `setState` in React, `inject`, etc. If we're not migrating to Vue3 never mind this question :)
[Blog Post Regarding this](https://dev.to/vuesomedev/you-might-not-need-vuex-with-vue-3-52e4)

**Comment by floydpink** [comment]
> * Do we really need `Vuex` for state management if we're gonna migrate to Vue v3? Vue3 has many helpful methods like the new `reactive` state functions (which are kinda like the state hooks in React like `setState`), `inject`, etc. If we're not migrating to Vue3 never mind this question :)
>   [Blog Post Regarding this](https://dev.to/vuesomedev/you-might-not-need-vuex-with-vue-3-52e4)

That looks really cool - thanks for sharing!

The fact that Vuex has a new major version (v4) ready for supporting Vue3 and that [the `Reactive API`](https://v3.vuejs.org/api/reactivity-api.html) is conspicuously missing in [the `Notable Features` in Vue3 official docs](https://v3.vuejs.org/guide/migration/introduction.html#notable-new-features), we should be okay bringing in Vuex.

For the port of the current functionality in the legacy AngularJS calendar as is, we might not really need Vuex or shared states - but I have some plans to make the new calendar more interactive with personalization, remembering Malayali birthdays (_pirannaalu_) etc. And that is why I thought bringing in Vuex might not be a bad idea.

Good question!

**Comment by carrotfarmer** [comment]
> 
> 
> > * Do we really need `Vuex` for state management if we're gonna migrate to Vue v3? Vue3 has many helpful methods like the new `reactive` state functions (which are kinda like the state hooks in React like `setState`), `inject`, etc. If we're not migrating to Vue3 never mind this question :)
> >   [Blog Post Regarding this](https://dev.to/vuesomedev/you-might-not-need-vuex-with-vue-3-52e4)
> 
> That looks really cool - thanks for sharing!
> 
> The fact that Vuex has a new major version (v4) ready for supporting Vue3 and that [the `Reactive API`](https://v3.vuejs.org/api/reactivity-api.html) is conspicuously missing in [the `Notable Features` in Vue3 official docs](https://v3.vuejs.org/guide/migration/introduction.html#notable-new-features), we should be okay bringing in Vuex.
> 
> For the port of the current functionality in the legacy AngularJS calendar as is, we might not really need Vuex or shared states - but I have some plans to make the new calendar more interactive with personalization, remembering Malayali birthdays (_pirannaalu_) etc. And that is why I thought bringing in Vuex might not be a bad idea.
> 
> Good question!

Thanks for the clarification!

**Review by carrotfarmer — APPROVED** [review]
Awesome!

**Comment by carrotfarmer** [comment]
@floydpink Oh, and we should probably convert the unit tests to TypeScript, right?

**Comment by floydpink** [comment]
> @floydpink Oh, and we should probably convert the unit tests to TypeScript, right?

yes - I was lazy to look up for an example and do it

interestingly, the vue-cli starter includes a `*.js` unit test even when the app itself is chosen to use TypeScript

**Comment by carrotfarmer** [comment]
> 
> 
> > @floydpink Oh, and we should probably convert the unit tests to TypeScript, right?
> 
> yes - I was lazy to look up for an example and do it
> 
> interestingly, the vue-cli starter includes a `*.js` unit test even when the app itself is chosen to use TypeScript

@floypink I wrote the unit tests in TypeScript (#31) but the e2e tests don't run (#32), and there seems to be reported issues of clashing types with Jest for eg: `it`, `describe` etc. Shoud we write the e2e tests in TypeScript too?

**Pull request merged**
