### PR TITLE
Add dependency checks and change favicon & app title

### PR DESCRIPTION
**Pull request by carrotfarmer**
**Changes**
- Add dependency checks with Dependabot
- Change the favicon to the Kollavarsham favicon from the old site
- Change the Page title to "Kollavarsham Calendar [BETA]"

### CODE REVIEW

**Review by floydpink — CHANGES_REQUESTED** [review]
Rather than update `index.html` directly and hard-code the title there, should we consider adding a `pages` object with a `title` property into `/vue-config.js` (as documented [here](https://cli.vuejs.org/config/#pages))?

**Comment by carrotfarmer** [comment]
> Rather than update `index.html` directly and hard-code the title there, should we consider adding a `pages` object with a `title` property into `/vue-config.js` (as documented [here](https://cli.vuejs.org/config/#pages))?
It errors out saying `title` is not a valid argument. Is this from the Vue v3 docs?
image

**Comment by carrotfarmer** [comment]
We can use the `created()` lifecycle hook inside of a component like so:
```js
<script>
export default {
    name: "Component",
    created() {
        document.title = "Page Title"
    }
}
</script>
```

but this would require changing the title in every component, or at least that's what I understand. We could try to do this inside the Main vue component.

**Comment by floydpink** [comment]
> > Rather than update `index.html` directly and hard-code the title there, should we consider adding a `pages` object with a `title` property into `/vue-config.js` (as documented [here](https://cli.vuejs.org/config/#pages))?
> 
> It errors out saying `title` is not a valid argument. Is this from the Vue v3 docs?
> image

Do you want to try the approach mentioned here?

https://stackoverflow.com/a/61109025/218882

**Comment by floydpink** [comment]
> We can use the `created()` lifecycle hook inside of a component like so:
> 
> ```js
> <script>
> export default {
>     name: "Component",
>     created() {
>         document.title = "Page Title"
>     }
> }
> </script>
> ```
> 
> but this would require changing the title in every component, or at least that's what I understand. We could try to do this inside the Main vue component.

Yes - as you mentioned, this would work - but not worth the additional overhead that it entails

**Comment by carrotfarmer** [comment]
> > > Rather than update `index.html` directly and hard-code the title there, should we consider adding a `pages` object with a `title` property into `/vue-config.js` (as documented [here](https://cli.vuejs.org/config/#pages))?
> > 
> > 
> > It errors out saying `title` is not a valid argument. Is this from the Vue v3 docs?
> > image
> 
> Do you want to try the approach mentioned here?
> 
> https://stackoverflow.com/a/61109025/218882

I tried that and it initially didn't work but after changing the title in `public/index.html` back to
```html
<title><%= htmlWebpackPlugin.options.title %></title>
```
it worked.
`vue.config.js`
```js
module.exports = {
    pages: {
        index: {
            entry: "src/main.js",
            template: "public/index.html",
            title: "Kollavarsham Calendar"
        }
    },
    publicPath: process.env.NODE_ENV === 'production'
        ? '/calendar-vue'
        : '/',
}
```

**Comment by floydpink** [comment]
> 
> I tried that and it initially didn't work but after changing the title in `public/index.html` back to
> 
> ```
> <title><%= htmlWebpackPlugin.options.title %></title>
> ```
> 
> it worked.
> `vue.config.js`
> 
> ```js
> module.exports = {
>     pages: {
>         index: {
>             entry: "src/main.js",
>             template: "public/index.html",
>             title: "Kollavarsham Calendar"
>         }
>     },
>     publicPath: process.env.NODE_ENV === 'production'
>         ? '/calendar-vue'
>         : '/',
> }
> ```

Awesome - thank you for figuring this out!

**Review by floydpink — APPROVED** [review]

**Review by floydpink — APPROVED** [review]
Thank you for these changes, @carrotfarmer !

**Comment by carrotfarmer** [comment]
You're welcome!

**Pull request merged**
